name: Deploy Mizuki to GitHub Pages
on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.1.3

      # 升级 Node 到 22，满足 pnpm11 最低版本要求
      - name: 配置Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 切换淘宝镜像
        run: pnpm config set registry https://registry.npmmirror.com

      - name: 构建静态站点
        run: |
          pnpm install
          pnpm build

      - name: 上传打包产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: 部署到Pages
        id: deploy
        uses: actions/deploy-pages@v4